apiVersion: v2
name: workshop-test
description: A Helm chart for Kubernetes
type: application
dependencies:
  - name: danibiri7-hello-world
    repository: "oci://ghcr.io/berezovsky15/helm"
    version: "1.0.4"
    alias: deploy1
  - name: danibiri7-hello-world
    repository: "oci://ghcr.io/berezovsky15/helm"
    version: 1.0.4
    alias: deploy2
version: 1.0.4
appVersion: "1.0.4"

metadata:
  name: '*****'
  annotations:
    argocd.argoproj.io/sync-wave: '{{ .Values.argocd.syncwave.deployment }}'
  