apiVersion: v2
name: workshop-test
description: A Helm chart for Kubernetes
type: application
dependencies:
  - name: danibiri7-hello-world
    repository: "oci://ghcr.io/berezovsky15/helm"
    version: "1.0.0"
    alias: deploy1
version: 1.0.0
appVersion: "1.0.0"
  